TREX-CoE/trexio

src/test.c
src/trexio.c
src/trexio.h
src/trexio.org
src/trexio_hdf5.h
src/trexio_hdf5.org
src/trexio_text.c
src/trexio_text.h
src/trexio_text.org

Lots of changes:
I Split the org file in 3 : front end, text and hdf.
I implemented locking on the file, so that only one process can access the file at a time. So now we can be sure that the image in memory is consistent with the file on disk, and we don't need to re-read it multiple times.
I also made a few changes in the front-end: error handling and trex_open instead of trex_create.
Valgrind gives no memory leaks in the text back end.

Rewrote text back end

---

src/test.c
src/trexio_hdf5.c
src/trexio_hdf5.org

fail when 'a' on non-existing file

Correct append

---

src/trexio_hdf5.c
src/trexio_hdf5.org

decoupling from the parent group, no need to read/write/free an entire parent group when reading scalars (e.g. dimensioning variables)

new read/write for numerical attributes

---

src/generator.py
src/templates_front/templator_front.org
src/templates_hdf5/build.sh
src/templates_hdf5/templator_hdf5.org
src/templates_text/build.sh
src/templates_text/templator_text.org
src/test.c
src/test.f90

1. `trexio_has_` functions introduced to check if a dimensioning variable or a dataset exists in the file
2. bug in text was due to the use of `%lf` option for `fprintf`:
- Problem: C outputs 6 decimal points for floating point numbers by default
- Solution: Specified the output format `%24.16e `

Add has_ functions everywhere + important bug fix in text backend

---

src/.gitignore
src/generator.py
src/templates_front/templator_front.org
src/test.c
src/test.f90

closes #7 
What has been done (in a nutshell):
1. Introduced API functions for I/O with single (`_32`) or double (`_64`) precision. The basic (i.e. when non-suffixed) API for `read/write_num` and `read/write_dset` is `_32` and `_64` respectively;
2. Front end org-mode file `templator_front.org` has been extensively documented.

Add 32-bit funcs and document front end

---

src/templates_hdf5/templator_hdf5.org
tools/generator.py

The use of `H5T_NATIVE_LONG`-like types was causing portability issues due to the differences with `stdint` types.
Fixed by switching `H5T_NATIVE_INT64` and use of generic `H5LTmake/read_dataset`.

More portable hdf5 back end

---

src/templates_front/templator_front.org
src/templates_hdf5/templator_hdf5.org
tools/build_trexio.sh
tools/generator.py
tools/generator_tools.py

Major changes in the `generator.py`:
1. modular structure of the code with calls to functions from external `generator_tools.py` module (added to the `tools/` directory);
2. previous dummy line transformation with `templine` variables replaced by calls to iterative and recursive replacers;
3. fixed a major bug with group names that was leading to some datasets appearing in the wrong files (e.g. datasets from `mo_1int` appearing in the `mo` group);
4. all functions in the `generator_tools.py` are annotated and contain a docstring.
Minor changes in the org-mode files:
1. removed "$group$\_" prefix from all "$group$\_$group\_*$" variables in the templates.

Major refactoring of the generator script

---

configure.ac
src/templates_front/build.sh
src/templates_front/templator_front.org
trex.org

This PR fixes #53 by automatically writing TREXIO version to the corresponding attribute of the `metadata` group upon creation of the TREXIO file.
Additionally, user name is now propagated all the way from the environment variable `$USER` to the corresponding constant definition in the `trexio.h` file. This is useful for re-solving #54, even though I am not convinced that we need it at the current stage.

Automatically add package version to the metadata; Close #53

---

docs/tutorial_benzene.html
src/pytrexio.i
src/templates_front/templator_front.org
src/templates_hdf5/templator_hdf5.org
src/templates_text/build.sh
src/templates_text/templator_text.org
tests/io_num_hdf5.c
tests/io_num_text.c
tools/generator.py
tools/generator_tools.py
trex.org

This PR closes #58.
It also introduces `dim` type in `trex.org` and the corresponding `trex.json`.
The numerical attributes with `dim` type are treated exactly like `int` with the only difference being that they cannot be negative or zero.
Attempt to write negative or zero `dim` attribute will result in `TREXIO_INVALID_NUM` exit code.

General numerical attributes (float, int, dim types)

---

python/test/test_api.py
src/pytrexio.i
src/templates_front/templator_front.org
tests/io_all.c
tests/io_dset_float_hdf5.c
tests/io_dset_float_text.c
tests/io_dset_int_hdf5.c
tests/io_dset_int_text.c
tests/io_dset_str_hdf5.c
tests/io_dset_str_text.c
tests/io_num_hdf5.c
tests/io_num_text.c
tests/io_safe_dset_float_hdf5.c
tests/io_safe_dset_float_text.c
tests/io_str_hdf5.c
tests/io_str_text.c
tests/open_hdf5.c
tests/open_text.c
tests/overwrite_all_hdf5.c
tests/overwrite_all_text.c
tests/test_f.f90

This PR closes #17.
Now `trexio_open` contains additional argument `trexio_exit_code* rc_open`, which can be modified within the function call and used to inspect the origin of error upon failure.
For example, an attempt to read a non-existing file will overwrite `rc_open` with an error code `TREXIO_OPEN_ERROR`, which can be handled accordingly. 
**Note:** in C and Fortran, the `rc_open` has to be defined before passing it as an argument to `trexio_open` function. In Python, the error code is used for exception handling and is not propagated back to the user.

Return error code from trexio_open

---

configure.ac
docker/build_manylinux_wheels.sh
python/pyproject.toml
python/requirements.txt
python/setup.py
src/numpy.i

This fix is needed due to the conflict of numpy versions when trexio is installed wheels. The solution is mainly based on the SciPy package. 
**Note:** the minimal version might have to be updated in the future!
Before, the wheels had the latest numpy (1.21) embedded, which was conflicting with the user numpy in the case of user numpy version ~=1.17.4.

Pin minimal required numpy versions

---

Makefile.am
README.md
configure.ac
python/test/test_pytrexio.py
src/templates_front/build.sh
src/templates_front/templator_front.org
tests/io_all.c
tests/test_f.f90
tools/prepare_python.sh

Introduced optional calls to HDF5 back end using the `#ifdef HAVE_HDF5` pre-processor macro, which value is defined by `configure` script in `config.h` file. 
By default, `./configure` proceeds to search for the HDF5 library. To disable this, provide `--without-hdf5` argument. For example,
`./configure --without-hdf5`

Compilation without HDF5

---

python/install_pytrexio.sh
python/test/test_api.py
src/templates_front/templator_front.org
src/templates_hdf5/templator_hdf5.org
src/templates_text/templator_text.org
tests/open_hdf5.c
tests/open_text.c
tests/test_f.f90

Implemented `trexio_inquire(file_name)` functions in C and Fortran APIs and `_inquire(file_name)` in Python API to check existence and validity of the `file_name` TREXIO file.
TREXIO file is valid if it satisfies one of the following conditions:
- an existing directory (should be opened with `TREXIO_TEXT` back end)
- an HDF5 file (should be opened with `TREXIO_HDF5` back end)

Add inquire functionality

---

python/test/test_api.py
src/templates_front/templator_front.org
tests/io_all.c
tests/open_hdf5.c
tests/open_text.c
tests/test_f.f90

This PR adds `TREXIO_AUTO` back end, which can be used in READONLY mode (`'r'`) to automatically determine the back end needed to open an existing TREXIO file. It does so by inspecting the return codes of `trexio_text_inquire` and `trexio_hdf5_inquire` functions. It should be updated when a new back end is implemented. 
`TREXIO_AUTO` only works together with `r` mode in `trexio_open`, i.e. the correct call pattern is as follows:
- `trexio_open(file_name, 'r', TREXIO_AUTO, &rc_open)`

Add auto backend

---

ChangeLog
src/templates_text/templator_text.org
tools/generator_tools.py

- Fixes #81 
In the meantime, the custom garbage collector from `generator_tools.py` which was deallocating previously allocated memory (datasets and strings) is no longer valid here since the order of allocation is arbitrary. However, the built-in `trexio_text_free_group` functions can be used as a garbage collector as long as the `file` handle contains a pointer to the allocated `group`.

refactor `trexio_text_read_group` set of functions to read data in an arbitrary order

---

Makefile.am
python/setup.py
python/test/test_api.py
src/pytrexio.i
src/templates_front/build.sh
src/templates_front/templator_front.org
src/templates_hdf5/build.sh
src/templates_hdf5/templator_hdf5.org
src/templates_text/build.sh
src/templates_text/templator_text.org
tests/CMakeLists.txt
tests/io_determinant_hdf5.c
tests/io_determinant_text.c
tests/test_f.f90
tools/generator.py
tools/generator_tools.py
trex.org

Determinants are stored as lists of `int64` bit fields for up- and down-spin electrons. CI coefficients are stored per state, namely one has to use `trexio_set_state(file, state_id)` function to read/write CI coefficients of state `state_id`.
Also implemented helper functions `trexio_to_orbital_list` and `trexio_to_orbital_list_up_dn` functions to convert a given determinant into a list of orbitals per spin component and for both components, respectively.
Added groups:
- `state`
- `determinant`
Note:
- One of the commits closes #90

Add I/O for determinants

---

trex.org

Following our discussion at UVSQ, I added a few entries in the `trex.org` file, namely `cell` group and imaginary parts (see `_im` suffix) of the following attributes:
- `mo_coefficient`
- all entries in `ao_1e_int` group
- all entries in `mo_1e_int` group
I have no experience with periodic calculations, so any comments/suggestions are welcomed.
This primarily concerns @ssorella and @kousuke-nakano.

Add ingredients for periodic calculations

---

.github/workflows/actions.yml
configure.ac
src/templates_front/templator_front.org
tests/io_all.c
tests/test_f.f90

@q-posev  : Sorry to bother you with another PR! :-)
This one is simple: I added a `trexio_cp(source, destination)` function to copy trexio files. It is handy because there are lots of cases where we want to copy a file and update the copy, and it is nicer than making a system call in the code.
I chose to use `/bin/cp`, because it is easy to copy both the HDF5 file or the directory tree of the Text back end. It is probably better than to try to re-implement cp which is supposed to be finely tuned...

Added trexio_cp

---

src/templates_front/templator_front.org
tests/test_f.f90

Suppose you have a determinant with 3 orbitals : |1 2 3>
If you store it in a bitfield, you get the integer 7 (111 in binary).
Now, if I have a determinant |1 3 2>, it also gives 7, but there is no way we can get back to |1 3 2>. We will go to |1 2 3>, and the problem is that |1 2 3> = -|1 3 2>. It imposes that the users are aware that they might need to compute a phase factor.
The helper function was modified to automatically compute the phase factor and returns the new exit code  `TREXIO_PHASE_CHANGE` if a change of sign is needed in the coefficient, so that the users can update the CI coefficients accordingly.

Introduced phase change

---

src/templates_front/templator_front.org

This change avoids `cppcheck` to create the warning:
```
trexio.c:48399:32: note: 'unique_rank' is assigned value '1' here.
const uint32_t unique_rank = 1;
^
trexio.c:48407:19: note: The expression 'unique_rank != 1' is always false.
if (unique_rank != 1) {
```

made unique_rank a preprocessor variable

---

Makefile.am
python/MANIFEST.in
python/setup.py
python/test/conftest.py
python/test/test_api.py
src/templates_front/templator_front.org
tests/io_dset_float_hdf5.c
tests/io_dset_float_text.c
tests/io_dset_int_hdf5.c
tests/io_dset_int_text.c
tools/prepare_python.sh

Text fallback when building python API

---

CMakeLists.txt
cmake/FindTREXIO.cmake
src/CMakeLists.txt

Hello everyone,
when compiling trexio with CMake as a subdirectory of a larger project, e.g. with the following structure:
Project/
&nbsp;&nbsp;src/
&nbsp;&nbsp;external/
&nbsp;&nbsp;&nbsp;&nbsp;trexio/
including trexio in the root CMakeLists.txt as ```add_subdirectory(external/trexio)``` has ```CMAKE_SOURCE_DIR``` pointing to ```Project``` instead of ```Project/external/trexio``` which breaks functionality. It is fixed by using ```PROJECT_SOURCE_DIR``` instead, which is identical to ```CMAKE_SOURCE_DIR``` if trexio is installed on its own.
Furthermore, I made ```FindTREXIO.cmake``` check whether ```TREXIO_DIR``` is set as a CMake variable before loading it from the environment variable.

CMake compilation as a subdirectory

---

README.md
src/templates_front/templator_front.org

I rewrote a few things in the readme.
I changed 
```
make -j`getconf _NPROCESSORS_ONLN`
```
because I think it was unnecessarily complicated. Also, I think that when you run with a very large number of cores, the Fortran module might not be compiled when expected. I put `make -j 4` because it is more deterministic.
Also, I added a section to specify that people can distribute TREXIO with their codes, and that they should use the release tarballs.

Updated readme

---

trex.org

I added just 2 entries in the rdm group: `1e_transition` and `2e_transition`
All the other differences are formatting of tables.

Added 1e and 2e transition density matrices for GammCor

---

trex.org

This should prevent having issues such as #127 and #142.

Added both row-major and column-major representations in documentation.

---

src/templates_front/templator_front.org

This PR fixes two problems with the Fortran API that I encountered while integrating TREXIO into CP2K:
1. The interface to `function trexio_info()` was returning an `integer` rather than a `c_int32_t`. To fix it @scemama and I used the same trick used for `function trexio_open`.
2. The `subroutine trexio_strarray2str` had an unused dummy argument, `max_str_len`, which we removed from the signature and for the relevant subroutine calls.

Fix interface return type and remove unused dummy argument

---

src/templates_front/templator_front.org

This fixes issue #146, please merge this after #145.
Note: The `import` statement imports the `iso_c_binding` elements from the module, so `use iso_c_binding` is not necessary inside the functions.

Improved modern fortran compliance

---

trex.org

I have added an array `kpoint` to the MO group.
With this modification, the users can store all the MOs of all kpoints in a single file. This is necessary because for correlated calculations (CI or CC), it is necessary to have 2-electron integrals involving MOs of different kpoints.
With this modification, it is possible to extend the format to correlated periodic calculations without breaking backwards compatibility.

Added kpoint to MO group

---

.github/workflows/actions.yml
Makefile.am
python/install_pytrexio.sh

First try macos-arm64

---

python/pyproject.toml
python/requirements.txt
src/numpy.i

Test numpy 2.0

---

.github/workflows/actions.yml
.github/workflows/build-wheels.yml
python/build_manylinux_wheels.sh

WIP: upgrade the wheel builds in our CI following recent deprecation (e.g. EOL Python < 3.8) and releases (Python 3.10+) in the Python ecosystem. Our custom manylinux Docker containers with HDF5 (from my [custom repo](https://github.com/q-posev/hdf5-on-manylinux)) have been upgraded too.
TODO: carefully check NumPy 1 vs 2 compatibility

Build and test new wheels (Python 3.10+ and manylinux tag 2.28 instead of 2.24)

---

README.md

I added a table with the codes that adopted TREXIO in one way or another. 
@scemama could you please check if I did not forget anything? Especially the `ipie` and `FHI-aims` sections (see `??` signs). I suppose there is no multi-reference I/O in FHI-aims and QMCkl?
@kousuke-nakano TurboRVB does not read multi-reference wave functions via TREXIO, right?
@stefabat Does CP2K support now both writing and reading (export and import) of the TREXIO (Hartree-Fock) wave functions?

Add codes supporting TREXIO

---

README.md
flake.lock
flake.nix
tools/nix/overlay.nix
tools/nix/trexio.nix
version_memo.txt

This adds Nix build instructions and a README section on its usage.

add nix build instructions and README section

---

trex.org

In periodic calculations, the Hartree-Fock exchange doesn't compensate well the periodic Coulomb part, and the Madelung constant has to be used to get the correct energy.

Add Madelung correction

---

.github/workflows/actions.yml
configure.ac
python/test/test_api.py
src/templates_front/templator_front.org
src/templates_text/templator_text.org
tests/io_determinant.c
tests/test_f.f90

- The text backend used 10 characters for storing 64-bit integers in text format, but this was too small. I changed it to 20 characters. Warning: This breaks backward-compatibility with the text backend!
- When you pass a list of determinants to the write function, it now checks that the number of alpha and beta occupied orbitals in the determinant is consistent with `nup` and `ndn`, and it also checks that the MO indices are in the correct range `[0:mo_num[`
- I had to update the Fortran test

Fix text backend for determinants + check consistency of determinants

---

README.md

Adds a reference to the Haskell bindings in the separate repository to the README.

add Haskell bindings section to README

---

Makefile.am
src/templates_front/templator_front.org
tools/build_json.sh
tools/build_trexio.sh
tools/emacs/config_tangle.el
trex.org

This should fix #180 
I modified the templates in the front-end to add line-continuation characters, so that the generated function names are alone in their line.

Fix long lines in Fortran

---

configure.ac
tools/build_json.sh

HDF5 detection was hard to understand in configure.ac
I tried to simplify the structure of the HDF5 detection.
`test .. == ..` is not portable, so I replaced by `test .. = ..`
In the original version, when `--with-hdf5=yes` is used:
- If `pkg-config` fails to find HDF5 and `h5cc` is not found, the script continues execution.
- It still defines `HAVE_HDF5`, appends empty flags, and fails later during library checks.
In the updated version:
- If `pkg-config` fails and `h5cc` is not found, it immediately errors out with:
`AC_MSG_ERROR([HDF5 not found: install pkg-config .pc file or h5cc, or use --with-hdf5=PATH])`
This short-circuits the process and prevents `HAVE_HDF5` from being defined.

Simplified configure.ac in hdf5

---

src/CMakeLists.txt

I think this step was missing for a pure cmake build? I need to look up CMAKE_CURRENT_ vs PROJECT_SOURCE_DIR before finalized for consideration.

cmake generation of trex.json

---

trex.org

Really fix #203 
Reading the documentation on the angular part, it is clear that the $r^\lambda$ factor is already included there, therefore $n_s=0$ also for Cartesian Gaussians!

Fix the Cartesian Gaussian definition
